### ISSUE TITLE
How does this make it easier to read?

### ISSUE THREAD

**Issue by G047** [SyntxProject/dScript.js#1]
Surly if you are shortening functions and names it makes it harder to understand, as you need know what each one does before you can use them. [this](https://www.w3.org/) is here for a reason.

**Comment by MastaCoder** [comment]
I'm closing this project. It was a project I ran on my free time to test out functions and scripts through JavaScript. I usually used it on my projects to see how short I can get functions to.

Only reason why it's still on GitHub is for referencing reasons. We have jQuery for a reason 😄

**Comment by G047** [comment]
Ah :)
